Replaced array_walk with array_map in Connection::getURI
elastic/elasticsearch-php pull request #1075
Opened 2020-10-26 11:01 UTC by pascaldevink

In Connection::getURI, array_walk was used together with passing the values as references, to change the original array.
Passing values as references is error-prone and discouraged for quite some time.
Also, when using in conjunction with PHP 8.0, it will fail.

array_map can do the same thing as the original array_walk implementation, but without the downsides of having side effects and having to pass values as references.

2020-10-26 11:01 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-11-16 15:23 UTC, mfn commented
This came up in https://github.com/elastic/elasticsearch-php/pull/1063#issuecomment-727770331

I took the changes in the PR and applied them to our local source tree in CI and can confirm that they work as intended!

2020-11-16 20:38 UTC, OskarStark approved these changes

2020-11-17 08:15 UTC, giovannialbero1992 commented
Hi @mfn, can we cherry-pick this into #1063 ?

2020-11-17 10:21 UTC, mfn commented
@giovannialbero1992 🤷‍♀️

I see what you mean, didn't realize that #1063 targets master and this PR targets `7.10`. Technically I don't see a reason not to.

However I'm not familiar with the process here, just a reported at this point :) I'm used to the multiple branch model that fixes will be applied to the lowest version (`7.10` here) and then merged upstream into master anyway? But I think I'm not qualified to answer this, sorry.

2020-11-26 16:09 UTC, pascaldevink commented
@deguif @giovannialbero1992 PHP 8 was released today, is there any update on the progress of this PR?

2020-12-10 16:04 UTC, deguif commented
@ezimuel this one should probably be merged to fully support PHP 8 , as it fails otherwise on PHP 8

2020-12-10 16:26 UTC, OskarStark requested changes

2020-12-10 16:26 UTC, OskarStark commented on tests/Elasticsearch/Tests/Connections/ConnectionTest.php
> +        /**
Indentation is wrong

2020-12-10 16:28 UTC, pascaldevink commented on tests/Elasticsearch/Tests/Connections/ConnectionTest.php
> +        /**
Fixed

2020-12-10 16:54 UTC, deguif commented
@pascaldevink it should probably target `7.x`, and would you able to rebase so that the test failure disappear as it seems it was fixed in this branch

2020-12-15 14:06 UTC, pascaldevink commented
@deguif @ezimuel rebased and updated the target against `7.x`. The tests are succeeding again as well

2020-12-16 21:29 UTC, merged

2020-12-16 21:32 UTC, ezimuel commented
@pascaldevink actually, it was enough to remove the `&$key` reference in the previous `array_walk` in order to be compatible with PHP 8 but your code was better, thanks!